fix some errors in update server hook

diff --git a/serverhooks/update b/serverhooks/update
--- a/serverhooks/update
+++ b/serverhooks/update
@@ -21,11 +21,12 @@ echo "Enforcing policies for revision ${refname}:"
 # -------------------------------
 
 # exit if a branch is about to be deleted
-if new == '0000000000000000000000000000000000000000':
+if [ "${newrev}" == '0000000000000000000000000000000000000000' ]; then
   exit 0
+fi
 
 # Check if a zero sha, then either a new branch is pushed or an empty repo is being pushed
-if [ "${oldrev}" = "0000000000000000000000000000000000000000" ]; then
+if [ "${oldrev}" == "0000000000000000000000000000000000000000" ]; then
   # List everything reachable from newrev but not any heads
   span=`git rev-list $(git for-each-ref --format='%(refname)' refs/heads/* | sed 's/^/\^/') ${newrev}`
 else
@@ -35,11 +36,12 @@ fi
 # ------------------------------------
 # Iterate over all commits in the push
 # ------------------------------------
+
 refuse=false
 for sha1 in ${span}; do
-
+  year=$(git log "${sha1}" --pretty=%cd -n 1| cut -d ' ' -f 5)
   # don't check commits from before 2020
-  if [ 2020 -le "$(git log "${sha1}" --pretty=%cd | cut -d ' ' -f 5)" ]; then
+  if [ "${year}" -lt '2020' ]; then
     continue
   fi
 
@@ -55,40 +57,41 @@ for sha1 in ${span}; do
   commitfirstline=$(echo "${commitmessage}" | head -n 1)
 
   # don't check revert commits
+  # TODO
   if [[ "${commitfirstline}" == Revert* ]]; then
     continue
   fi
 
   # if commitmessage has 2 or more lines, make sure the second line is empty
   if [ $(echo "${commitmessage}" | wc -l) -ge 2 ]; then
-    if [ $(echo "${commitmessage}" | head -n 2 | tail -n 2) != "" ]; then
-      echo "commit: ${sha1}"
-      echo "bad commit message: second line is not blank"
+    if [ "$(echo "${commitmessage}" | head -n 2 | tail -n 2)" != "" ]; then
+      echo "${sha1} bad commit message; second line is not blank"
       refuse=true
     fi
   fi
 
   # check length of commit description lines
-  for line in ${commitmessage}; do
+  while IFS= read -r line; do
     if [ 75 -lt $(echo ${line} | wc -c) ]; then
-      echo "commit: ${sha1}"
-      echo "bad commit message: header or description lines are too long (max 75 chars)"
+      echo "${sha1} bad commit message; header or description lines are too long (max 75 chars per line)"
       refuse=true
       break
     fi
-  done
+  done <<< "${commitmessage}"
 
   # check for whitespace errors in commit
   whitespace=$(exec git diff --check ${sha1}^ ${sha1} *.c *.h *.cpp *.hpp *.sh)
   if [ "${whitespace}" != "" ]; then
-    echo "commit: ${sha1} contains whitespace errors."
+    echo "${sha1} contains whitespace errors."
     refuse=true
   fi
 done
 
 if [ "${refuse}" == true ]; then
   echo "Found errors, please fix them before pushing."
+  exit 1
 else
   echo "All good, thank you!"
 fi
 
+exit 1
