also check for missing newlines

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -45,6 +45,32 @@ if [ "${whitespace}" != "" ]; then
   exit 1
 fi
 
+
+# Files (not deleted) in the index
+files=$(git diff-index --cached --name-only --diff-filter=d "$against")
+result=0  # track exit code
+if [ -n "$files" ]; then
+  for f in $files; do
+    # Only report known text files...
+    if [ -z "$(git diff-index --cached --stat=1 "$against" "$f" | grep -is '| Bin')" ]; then
+      # Only match regular files (e.g. no symlinks)
+      # See: https://stackoverflow.com/a/8347325
+      if [ "$(git ls-files --stage "$f" | awk '{print $1}' | head -c2 - )" = "10" ]; then
+        # Using staged version of file instead of working dir
+        # See: http://stackoverflow.com/a/5032436/5343341
+        if [ -n "$(git cat-file blob "$(git ls-files --stage "$f" | awk '{print $2}')" | tail -c1 - )" ]; then
+          # Report error
+          if [ "$result" -lt "1" ]; then
+            echo "Error: The following files have no trailing newline:"
+          fi
+          echo "$f"
+          exit 1
+        fi
+      fi
+    fi
+  done
+fi
+
 # check for `#if 0` in the code
 ifzeros=$(git diff --cached HEAD *.c *.h *.cpp *.hpp *.sh | grep "^+" | grep "#if[[:space:]]\+0")
 echo "> Checking occurences of '#if 0'."
